"""Default-off contracts for isolated workspace-coding tasks."""

from workspace_coding.adoption import (
    WorkspaceAdopter,
    WorkspaceAdoptionChoice,
    WorkspaceAdoptionError,
    WorkspaceAdoptionReceipt,
    WorkspaceAdoptionRequest,
    WorkspaceDiffEntry,
    WorkspaceDiffReview,
    WorkspaceReviewFormat,
    build_workspace_diff_review,
    workspace_adoption_action_digest,
)
from workspace_coding.broker import (
    WorkspaceBroker,
    WorkspaceBrokerError,
    WorkspaceCommandLauncher,
)
from workspace_coding.models import (
    CommandProfile,
    GitWorkspaceIdentity,
    IsolatedWorkspaceResult,
    VerificationReceipt,
    WorkspaceChange,
    WorkspaceChangeKind,
    WorkspaceCommandRequest,
    WorkspaceDeleteRequest,
    WorkspaceFileRecord,
    WorkspaceManifest,
    WorkspaceMkdirRequest,
    WorkspaceReadRequest,
    WorkspaceWriteRequest,
    workspace_action_digest,
)
from workspace_coding.sandbox import (
    SandboxConfiguration,
    SandboxConfigurationError,
    generate_sandbox_configuration,
    verify_isolated_result,
)
from workspace_coding.snapshot import (
    WorkspaceSnapshot,
    WorkspaceSnapshotError,
    create_isolated_snapshot,
    inspect_selected_git_workspace,
)

__all__ = [
    "CommandProfile",
    "GitWorkspaceIdentity",
    "IsolatedWorkspaceResult",
    "SandboxConfiguration",
    "SandboxConfigurationError",
    "VerificationReceipt",
    "WorkspaceAdopter",
    "WorkspaceAdoptionChoice",
    "WorkspaceAdoptionError",
    "WorkspaceAdoptionReceipt",
    "WorkspaceAdoptionRequest",
    "WorkspaceBroker",
    "WorkspaceBrokerError",
    "WorkspaceChange",
    "WorkspaceChangeKind",
    "WorkspaceCommandLauncher",
    "WorkspaceCommandRequest",
    "WorkspaceDeleteRequest",
    "WorkspaceDiffEntry",
    "WorkspaceDiffReview",
    "WorkspaceFileRecord",
    "WorkspaceManifest",
    "WorkspaceMkdirRequest",
    "WorkspaceReadRequest",
    "WorkspaceSnapshot",
    "WorkspaceSnapshotError",
    "WorkspaceWriteRequest",
    "WorkspaceReviewFormat",
    "build_workspace_diff_review",
    "create_isolated_snapshot",
    "generate_sandbox_configuration",
    "inspect_selected_git_workspace",
    "verify_isolated_result",
    "workspace_action_digest",
    "workspace_adoption_action_digest",
]
